/**
 * SECURITY: HMAC-signed OAuth state parameter.
 * Prevents CSRF attacks by ensuring the state parameter
 * was generated by our server and hasn't been tampered with.
 */

import { createHmac, randomBytes } from "crypto";

function getSecret(): string {
  // Use a dedicated secret or fall back to SUPABASE_SERVICE_ROLE_KEY
  return (
    process.env.OAUTH_STATE_SECRET ||
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    "fallback-dev-only"
  );
}

/**
 * Create a signed OAuth state parameter containing the user ID.
 * Format: base64url(JSON({ userId, nonce, sig }))
 */
export function createOAuthState(userId: string): string {
  const nonce = randomBytes(16).toString("hex");
  const payload = JSON.stringify({ userId, nonce });
  const sig = createHmac("sha256", getSecret()).update(payload).digest("hex");
  return Buffer.from(JSON.stringify({ userId, nonce, sig })).toString(
    "base64url",
  );
}

/**
 * Verify and decode a signed OAuth state parameter.
 * Returns the userId if valid, null if tampered or invalid.
 */
export function verifyOAuthState(state: string): string | null {
  try {
    const decoded = JSON.parse(Buffer.from(state, "base64url").toString());
    const { userId, nonce, sig } = decoded;

    if (!userId || !nonce || !sig) return null;

    const payload = JSON.stringify({ userId, nonce });
    const expectedSig = createHmac("sha256", getSecret())
      .update(payload)
      .digest("hex");

    // Constant-time comparison
    if (sig.length !== expectedSig.length) return null;
    let mismatch = 0;
    for (let i = 0; i < sig.length; i++) {
      mismatch |= sig.charCodeAt(i) ^ expectedSig.charCodeAt(i);
    }
    if (mismatch !== 0) return null;

    return userId;
  } catch {
    return null;
  }
}
